name:       hlinq
version:    0.1.0.0
author:     carp-sushi
maintainer: 105142707+carp-sushi@users.noreply.github.com

dependencies:
  - base

library:
  source-dirs: src

tests:
  hlinq-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlinq
    - hspec
    - tasty
    - tasty-hspec
